import { AgentPlan } from "@/lib/types";

export const MOCK_PLAN: AgentPlan = {
  sessionId: "template-h1b",
  userContext: {
    visaType: "H-1B Specialty Occupation",
    deadline: "2025-03-01",
    currentStatus: "F-1 Student on OPT",
    location: "United States",
    initialPrompt: "What documents do I need for my H-1B visa application?",
  },
  planSummary: {
    headline: "Secure Your H-1B Work Authorization",
    overview: [
      "Complete the USCIS H-1B petition with supporting evidence to demonstrate the job qualifies as a specialty occupation.",
      "Coordinate with your sponsoring employer to pay filing fees and submit the LCA certification.",
      "Prepare for next steps after petition approval, including visa stamping and work authorization start dates.",
    ],
    keyMetrics: [
      { label: "Government Filing Fees", value: ",710–,960" },
      { label: "Typical Processing Time", value: "3–6 months (regular)" },
      { label: "Premium Processing", value: ",805 (15 Calendar Days)" },
    ],
  },
  workstreams: [
    {
      id: "doc-prep",
      title: "Document Preparation",
      icon: "FileText",
      progress: 75,
      successRate: {
        successful: 46,
        total: 50,
      },
      steps: [
        {
          id: "passport",
          name: "Gather Valid Passport",
          status: "complete",
          description: "Ensure your passport is valid for at least 6 months beyond your intended stay.",
          priority: "high",
          deadline: "2025-11-01",
          estimatedTime: "1-2 days",
          confidenceScore: 98,
          instructions: [
            "Check passport expiration date - must be valid for 6 months beyond travel date.",
            "Ensure at least 2 blank pages are available for visa stamps.",
            "Make 2 photocopies of the information page.",
            "Verify there is no physical damage to the passport.",
          ],
          visualCaption: "Example of valid passport information page.",
          documentRequired: true,
          sources: [
            {
              id: "uscis-passport",
              title: "USCIS Passport Requirements",
              url: "https://travel.state.gov/content/travel/en/us-visas/visa-information-resources/photos.html",
              type: "official",
              lastVerified: "2025-01-15",
            },
            {
              id: "state-travel-guide",
              title: "State Department Travel Guide",
              url: "https://travel.state.gov",
              type: "official",
              lastVerified: "2025-01-10",
            },
          ],
        },
        {
          id: "photos",
          name: "Prepare Visa Photos",
          status: "complete",
          description: "Get compliant passport photos taken.",
          priority: "high",
          estimatedTime: "30 minutes",
          confidenceScore: 95,
        },
        {
          id: "financial",
          name: "Financial Documents",
          status: "in-progress",
          description: "Gather proof of financial support.",
          priority: "high",
          deadline: "2025-11-15",
          estimatedTime: "3-5 days",
          confidenceScore: 92,
          instructions: [
            "Collect bank statements for the last 6 months.",
            "Obtain a letter from your sponsor if applicable.",
            "Prepare tax returns for the last 2 years.",
            "Compile proof of assets (property deeds, investment statements).",
          ],
          documentRequired: true,
          sources: [
            {
              id: "financial-evidence",
              title: "Financial Evidence Requirements",
              url: "https://www.uscis.gov/i-129",
              type: "official",
              lastVerified: "2025-01-20",
            },
          ],
        },
        {
          id: "supporting",
          name: "Supporting Documents",
          status: "pending",
          description: "Gather additional required documentation.",
          priority: "medium",
          estimatedTime: "2-3 days",
        },
      ],
    },
    {
      id: "form-filling",
      title: "Form Filing",
      icon: "FileEdit",
      progress: 40,
      steps: [
        {
          id: "lca",
          name: "Labor Condition Application (LCA)",
          status: "in-progress",
          description: "Employer files ETA-9035 with the Department of Labor.",
          priority: "high",
          deadline: "2025-10-15",
          estimatedTime: "7 business days",
          confidenceScore: 90,
          instructions: [
            "Prepare job offer details (title, wage, location).",
            "Verify prevailing wage determination.",
            "Submit ETA-9035 via the FLAG portal.",
            "Wait for certification before filing Form I-129.",
          ],
          sources: [
            {
              id: "dol-flag",
              title: "DOL FLAG System Guidance",
              url: "https://flag.dol.gov/",
              type: "official",
              lastVerified: "2025-01-12",
            },
          ],
        },
        {
          id: "i129",
          name: "Form I-129 Petition",
          status: "pending",
          priority: "high",
          description: "Employer completes and submits Form I-129 with supporting evidence.",
          instructions: [
            "Complete the H Classification Supplement.",
            "Attach employer support letter detailing job duties.",
            "Include educational transcripts and evaluation.",
            "Add itinerary if multiple worksites are involved.",
          ],
        },
        {
          id: "receipt",
          name: "USCIS Receipt Notice",
          status: "locked",
        },
      ],
    },
    {
      id: "appointment",
      title: "Visa Stamping",
      icon: "Calendar",
      progress: 0,
      steps: [
        {
          id: "fee",
          name: "Pay Visa Fee",
          status: "pending",
          priority: "high",
        },
        {
          id: "schedule",
          name: "Schedule Interview",
          status: "locked",
        },
        {
          id: "prepare",
          name: "Interview Preparation",
          status: "locked",
        },
      ],
    },
    {
      id: "arrival",
      title: "Post-Approval",
      icon: "MessageSquare",
      progress: 0,
      steps: [
        {
          id: "approval",
          name: "Petition Approval",
          status: "locked",
        },
        {
          id: "stamping",
          name: "Consular Processing",
          status: "locked",
        },
        {
          id: "start-date",
          name: "Begin Employment",
          status: "locked",
        },
      ],
    },
  ],
  checklist: [
    {
      id: "passport-copy",
      label: "Passport biographical page copy",
      status: "complete",
      notes: "Uploaded to employer portal",
      relatedStepId: "passport",
      sourceId: "uscis-passport",
    },
    {
      id: "degree-evaluation",
      label: "Degree equivalency evaluation",
      status: "in-progress",
      notes: "Waiting on credential service report",
      relatedStepId: "i129",
    },
    {
      id: "client-letter",
      label: "End client letter confirming worksite",
      status: "pending",
      relatedStepId: "i129",
    },
  ],
  timeline: [
    {
      id: "lca-cert",
      title: "LCA Certification",
      description: "DOL typically processes LCAs within 7 business days.",
      dueDate: "2025-10-22",
      sourceId: "dol-flag",
    },
    {
      id: "uscis-filing",
      title: "USCIS Form I-129 Filing Window",
      description: "USCIS opens the cap-subject filing window on April 1 each year.",
      dueDate: "2025-04-01",
      sourceId: "financial-evidence",
    },
    {
      id: "start-date",
      title: "H-1B Employment Start",
      description: "Earliest employment start date is October 1 for cap-subject cases.",
      dueDate: "2025-10-01",
    },
  ],
  sources: [
    {
      id: "uscis-passport",
      title: "USCIS Passport Requirements",
      url: "https://travel.state.gov/content/travel/en/us-visas/visa-information-resources/photos.html",
      type: "official",
      lastVerified: "2025-01-15",
    },
    {
      id: "state-travel-guide",
      title: "State Department Travel Guide",
      url: "https://travel.state.gov",
      type: "official",
      lastVerified: "2025-01-10",
    },
    {
      id: "financial-evidence",
      title: "Form I-129 Evidence Requirements",
      url: "https://www.uscis.gov/i-129",
      type: "official",
      lastVerified: "2025-01-20",
    },
    {
      id: "dol-flag",
      title: "DOL FLAG System Guidance",
      url: "https://flag.dol.gov/",
      type: "official",
      lastVerified: "2025-01-12",
    },
  ],
  hitl: {
    required: false,
    message: "",
  },
};
